* evil mode as a backbone

Let's define some states:
- insert
- movement
- edit
That's all as far as I know it. Later vi-like modes like visual are
to be considered.

For all states that allows to type (emacs, insert), the mode
switching should be C-{key from right side of the keyboard}. What
keys do we have to bind?

1. Switching to emacs state should be available in every state. So,
   write the macro that traverses all states and sets C-z keybinding to
   this mode. First, set foo-all-states variable:

   (set foo-all-states
    ('evil-insert-state
     'evil-normal-mode
     'evil-movement-mode))

2. Switching between modes. Two possible designs:

   a) For every pair twice
   b) every mode can return to emacs state and normal-mode; switching
      to other modes only in normal-mode.

* startup stuff in its own file from the begining
* directories for each state
* special states for shell, magit that might derive from other modes
** two shell states that derives from: insert and movement states
** magit derives from movement
* use a lot of variables
** do not define font name in code, use variable for that
*** advantage is that you can set the variables conditionaly
This feature should be very useful on Windows, where I am too lazy to
install all the fonts I need.
